name: "tagged-release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tagged-release:
    name: "Webport Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build & test"
      - uses: actions/checkout@v3
      - name: Use Node.js 1.18
        uses: actions/setup-node@v3
        with:
          node-version: 1.18
          cache: 'npm'
      - run: |
          npm ci
          npm run build:webport

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            webport/dist/index.html
